appveyor.yml, packer.nuspec, tools/chocolateyInstall.ps1
Update Packer 0.12.1 which adds Hyper-V builder
=> Update Packer 0.12.1

appveyor.yml, packer.nuspec, tools/chocolateyInstall.ps1
Update Packer 0.12.2
Signed-off-by: Stefan Scherer <scherer_stefan@icloud.com>
=> Update Packer 0.12.2

appveyor.yml, packer.nuspec, tools/chocolateyInstall.ps1
Can add git tag with new version when appveyor passes
=> Update Packer 1.2.5

appveyor.yml, packer.nuspec, tools/chocolateyInstall.ps1
Update version and check-sums for Packer 1.4.1
=> Update Packer 1.4.1

appveyor.yml, packer.nuspec, tools/chocolateyInstall.ps1
Packer 1.7.1 Changelog: https://github.com/hashicorp/packer/blob/v1.7.1/CHANGELOG.md#171-march-31-2021
=> Update to Packer 1.7.2

appveyor.yml, packer.nuspec, tools/chocolateyInstall.ps1
Updates packer to 1.7.3
@StefanScherer
=> update to packer 1.7.3

appveyor.yml, packer.nuspec, tools/chocolateyInstall.ps1
Update Packer to [1.7.10](https://github.com/hashicorp/packer/releases/tag/v1.7.10)
=> Update Packer to 1.7.10

appveyor.yml, packer.nuspec, tools/chocolateyInstall.ps1
Source: https://github.com/hashicorp/packer/blob/v1.8.0/CHANGELOG.md
=> Update to 1.8.0

packer.nuspec, tools/chocolateyInstall.ps1
Cherry-picked commit from #75 and resolved the conflict.
=> Update Packer to 1.8.4

.github/workflows/release.yml
Signed-off-by: Stefan Scherer <scherer_stefan@icloud.com>
=> Fix GH workflow for release

packer.nuspec, tools/chocolateyInstall.ps1
Signed-off-by: Stefan Scherer <scherer_stefan@icloud.com>
=> Update Packer 1.8.5

packer.nuspec, tools/chocolateyInstall.ps1
Updates package to Packer 1.8.6
=> Update to Packer 1.8.6

packer.nuspec, tools/chocolateyInstall.ps1
Updates package to Packer 1.8.7
=> Update to Packer 1.8.7

packer.nuspec, tools/chocolateyInstall.ps1
Updates package to Packer 1.9.0
=> Update to Packer 1.9.0

packer.nuspec, tools/chocolateyInstall.ps1
Updates package to Packer 1.9.1
=> Update Packer to 1.9.1

packer.nuspec, tools/chocolateyInstall.ps1
Updates package to Packer 1.9.2
=> Update Packer to 1.9.2

packer.nuspec, tools/chocolateyInstall.ps1
Updates package to Packer 1.9.3
=> Update Packer to 1.9.3

packer.nuspec, tools/chocolateyInstall.ps1
Updates package to Packer 1.9.4
=> Update Packer to 1.9.4

packer.nuspec, tools/chocolateyInstall.ps1
=> Update Packer to 1.10.0

packer.nuspec, tools/chocolateyInstall.ps1
[Packer 1.11.2](https://github.com/hashicorp/packer/releases/tag/v1.11.2)
=> Packer 1.11.2
